Adding storage retention to logging and observability
OCP-on-NERC/nerc-ocp-config pull request #165
Opened 2022-11-29 20:13 UTC by computate

- Adding 90 day retention for audit logs as suggested by the [NERC Operational Use Cases](https://docs.google.com/document/d/1dHHpWvJD4b1mdXTDQhgWhiGeOLY7N7FmwvgI5VB3tP0/edit) useful for security audits.
- Adding 30 day retention for application and infrastructure logs.
- Configuring 90 days to retain samples of resolution 1 (5 minutes) in a bucket for Observability as well as already existing defaults.

## Issues:
This relates to a couple of issues, to avoid running out of disk space: 
- https://github.com/OCP-on-NERC/operations/issues/38
- https://github.com/OCP-on-NERC/operations/issues/39

## Documentation:
- [See retention configuration for Loki](https://loki-operator.dev/docs/api.md/#loki-grafana-com-v1-LimitsTemplateSpec#loki-grafana-com-v1-LimitsTemplateSpec)
- [See retention configuration for Observability](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.5/html-single/apis/index#rhacm-docs_apis_multiclusterobservability_jsonmulticlusterobservability_observabilityretention)

2022-11-29 20:25 UTC, naved001 approved these changes

2022-11-30 16:59 UTC, computate commented
I am following up with the Loki Operator team on their Slack channel, because after upgrading manually to the latest Loki Operator 5.5.4 provided by Red Hat OpenShift in the infra cluster, it still doesn't provide the [RetentionLimitSpec spec as defined in the v1 API](https://loki-operator.dev/docs/api.md/#loki-grafana-com-v1-LimitsTemplateSpec). I am unsuccessful applying retention to my LokiStack, only ingestion and queries.

```yaml
apiVersion: loki.grafana.com/v1
kind: LokiStack
spec:
  limits:
    global:
      retention:
        days: 90
```

2022-12-01 14:48 UTC, larsks requested changes
@computate As I understand it, we're putting this PR on hold right now because the syntax it uses for configuring retention in Loki isn't supported by the version of the operator we're currently running.

Is that accurate?

2022-12-01 15:15 UTC, computate commented
That is correct @larsks . These commits in this PR https://github.com/grafana/loki/pull/7106 from Grafana Loki have been merged into OpenShift Loki https://github.com/openshift/loki/commit/9bee101abab46245bd70ea78c9bb734a1e4eb852, but the latest version of the [Red Hat Loki Operator `v5.5.4-4`](https://catalog.redhat.com/software/containers/openshift-logging/loki-rhel8-operator/622b46bcae289285d6fcda39?container-tabs=technical-information) does not yet include these commits containing `RetentionStreamSpec`. [See the lokistack_types.go file](https://github.com/openshift/loki/blob/ab214c02e86c997fa86848aa84dadfb3277e3459/operator/apis/loki/v1/lokistack_types.go). I will close this for now.

2022-12-01 15:15 UTC, closed without merging