Patch nerc-secret-store in test cluster overlay
OCP-on-NERC/nerc-ocp-config pull request #208
Opened 2023-03-14 16:31 UTC by dystewart

Patches the nerc-secret-store in the test cluster to use test cluster k8s auth method in vault

2023-03-14 18:56 UTC, computate approved these changes

2023-03-15 15:48 UTC, computate approved these changes

2023-03-16 11:24 UTC, larsks requested changes

2023-03-16 11:24 UTC, larsks commented on cluster-scope/overlays/nerc-ocp-test/feature/odf/components/nerc-secret-store/secretstore.yaml
To avoid confusion, I would avoid naming a directory "components" unless it actually contains Kustomize components (e.g., https://github.com/OCP-on-NERC/nerc-ocp-config/tree/main/cluster-scope/components).

2023-03-16 11:24 UTC, larsks commented on cluster-scope/overlays/nerc-ocp-test/feature/odf/components/nerc-secret-store/secretstore.yaml
Also, this should probably be consuming the `nerc-secret-store` component, and then just patch the `spec.provider.auth.kubernetes.mountPath` value, rather than replacing most of the resource:

```
patches:
  - patch: |
      apiVersion: external-secrets.io/v1beta1
      kind: SecretStore
      metadata:
        name: nerc-secret-store
      spec:
        provider:
          vault:
            auth:
              kubernetes:
                mountPath: kubernetes/nerc-ocp-test
```

(You could of course put this in a file instead of including it inline -- the salient change is that we're just patching the specific value that needs to be updated.)

2023-03-17 21:15 UTC, dystewart commented on cluster-scope/overlays/nerc-ocp-test/feature/odf/components/nerc-secret-store/secretstore.yaml
@larsks In the interest of keeping the overlay as clean as possible added the streamlined patch via a file

2023-04-05 17:03 UTC, larsks approved these changes

2023-04-05 17:03 UTC, merged