Install Apache Solr Operator Helm Chart Repository and CRDs to prod
OCP-on-NERC/nerc-ocp-config pull request #236
Opened 2023-04-17 18:28 UTC by computate

The [Smart Village Collaboratory project](https://research.redhat.com/blog/research_project/creating-a-global-open-research-platform-to-better-understand-social-sustainability-using-data-from-a-real-life-smart-village/) would like to install the Apache Solr Operator and CRDs to NERC. There are two important parts here. The Apache Zookeeper cluster for running Solr as a clustered cloud, as well as our smart village application which is a Vert.x application that is also clustered between pods with the Apache Zookeeper cluster. The second part is Apache Solr which is the search engine for the Smart Village application. The search engine powers the API for extremely fast querying, pagination, filtering, faceting, pivoting, sorting and more. This allows for building custom analytics and dashboards that are extremely powerful. You can find the [CRDs for Apache Solr](https://solr.apache.org/operator/downloads/crds/v0.6.0/all-with-dependencies.yaml) here, and the [Helm Chart Repository for Apache Solr](https://github.com/computate-org/smartabyar-smartvillage/blob/main/openshift/kustomize/bundles/solr/base/helmchartrepositories/solr-helm-repo/helmchartrepository.yaml) here. 

Close https://github.com/OCP-on-NERC/operations/issues/110

2023-05-24 19:41 UTC, jtriley reviewed
LGTM. @larsks Would you prefer to have these CRDs in base instead (e.g. `cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions`)?

2023-05-30 15:33 UTC, aabaris approved these changes

2023-05-30 16:15 UTC, larsks approved these changes

2023-05-30 16:15 UTC, larsks commented on cluster-scope/bundles/solr-helm-repo/solrbackups.yaml
Subdirectories of the `bundles` directory should only contain `kustomization.yaml` files.

2023-05-30 16:15 UTC, larsks requested changes
Sorry, previous review should have been "request changes".

2023-05-30 16:45 UTC, computate commented on cluster-scope/bundles/solr-helm-repo/solrbackups.yaml
Sure @larsks , I moved the CRDs to `cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/solr-helm-repo`

2023-05-30 16:47 UTC, larsks approved these changes

2023-05-30 16:49 UTC, jtriley approved these changes

2023-05-30 16:55 UTC, merged