Add: k8s login logic for vault backup job
OCP-on-NERC/nerc-ocp-config pull request #267
Opened 2023-08-02 16:34 UTC by dystewart

Closes issue https://github.com/OCP-on-NERC/operations/issues/112

Updates the vault backup job to renew vault token upon each taskrun, so we won't have to do so manually

2023-08-03 19:37 UTC, larsks requested changes
Please update the commit message to include additional details. The content of the PR description would be sufficient.

2023-08-03 21:19 UTC, jtriley approved these changes

2023-08-10 19:54 UTC, dystewart commented
@larsks Just want to make sure you see this, since not sure if the review request made it on your radar

2023-08-14 18:42 UTC, larsks approved these changes

2023-08-16 13:44 UTC, merged