Custom grafana dashboard
OCP-on-NERC/nerc-ocp-config pull request #317
Opened 2023-11-13 16:23 UTC by jbasu01

A new custom Grafana dashboard was created and tested by bringing in metrics from ArgoCD. ArgoCD provides a JSON template download, and code from the JSON download could be copied into the config file and appropriate changes made to ensure metrics from ArgoCD dashboard are pulled in and made visible in the custom Grafana dashboard. Additional information is available at https://grafana.com/grafana/dashboards/14584-argocd/

A key item to make a note of is that one cannot use the word "ArgoCD" or "argocd" just by itself in the value for the key "title" in the grafana-dashboard-argocd.yaml.  When changed to "ArgoCD xxxxx" ("ArgoCD stats" in our case and it worked fine.

2023-11-13 16:38 UTC, schwesig commented
@schwesig

2023-11-13 22:44 UTC, larsks commented
> A key item to make a note of is that one cannot use the word "ArgoCD" or "argocd" just by itself in the value for the key "title" in the grafana-dashboard-argocd.yaml.

Why?

2023-11-16 16:11 UTC, schwesig approved these changes
working together with Jeet in a call
checking and linting together

2023-11-16 22:19 UTC, computate commented
@jbasu01 @schwesig Nice job resolving the pre-commit hooks and squashing to one commit. I just want to test this out together in an upcoming meeting on Monday, update the datasources, and make sure it's ready. I realize @jbasu01 will be on vacation, but we can work out the final details next week.

2023-11-16 22:21 UTC, computate commented
@larsks after a couple hours going crazy testing out a custom dashboard in the ACM grafana, I can't explain why, but naming the dashboard anything but `argocd` or `ArgoCD` magically made the dashboard work.

2023-11-19 14:12 UTC, schwesig commented
@computate thanks for checking the argocd naming problem we had and confirming it.

2023-11-28 03:00 UTC, larsks requested changes

2023-11-28 03:00 UTC, larsks commented on grafana/base/grafanadatasources/grafanadatasource.yaml
> +        tlsSkipVerify: true
Are you sure this is necessary? You should be able to use the ca cert provided in `/run/secrets/kubernetes.io/serviceaccount` to trust other services on the cluster without disabling tls verification.

2023-11-28 03:00 UTC, larsks commented on grafana/base/grafanas/grafana.yaml
> +      root_url: $GRAFANA_ROOT_URL
I would avoid placeholders that look like variables (because some might be confused about how things operate). Consider something like...

```suggestion
      root_url: REPLACE_IN_OVERLAY
```

2023-11-28 03:00 UTC, larsks commented on grafana/base/kustomization.yaml
> +  #  - grafanadatasources
If we don't need this, remove it. If it's meant as an example, then add a comment documenting why it's here.

2023-11-28 03:00 UTC, larsks commented on grafana/base/routes/route.yaml
> +  host: grafana.apps.nerc-ocp-infra.rc.fas.harvard.edu
You should treat this the same way you treat `root_url` in `base/grafanas/grafana.yaml`.

2023-11-28 03:00 UTC, larsks commented on grafana/base/serviceaccounts/serviceaccount.yaml
> +---
Remove the YAML document separator (you're not using it anywhere else).

2023-11-28 03:00 UTC, larsks commented on grafana/overlays/nerc-ocp-infra/kustomization.yaml
> +  - grafanas/logging-grafana_patch.yaml
This should be:

```suggestion
patches:
- path: grafanas/logging-grafana_patch.yaml
```

`patchesStrategicMerge` has been [deprecated for a while](https://github.com/kubernetes-sigs/kustomize/issues/5052).

2023-11-29 15:41 UTC, schwesig commented
@larsks Thanks for your feedback.
@jbasu01 next steps to work on for us

2023-11-29 22:16 UTC, computate commented
@larsks I'm having trouble with the Patch Operator with this PR. I have applied the changes from this branch to test it: 

```
oc --as system:admin apply -k grafana/overlays/nerc-ocp-infra/
```

The Patches say `LastReconcileCycleSucceded`: 

```bash
oc --as system:admin -n grafana get patch/grafana-oauth -o yaml | grep 'status:' -A 20
oc --as system:admin -n grafana get patch/grafanadatasource-observability-metrics -o yaml | grep 'status:' -A 20
```

But the objects are not patched: 

```bash
oc --as system:admin -n grafana get grafana/grafana -o yaml | grep 'root_url:'
oc --as system:admin -n grafana get grafanadatasource/observability-metrics -o yaml | grep 'secureJsonData:' -A 2
```

@larsks Can you please help me understand why the patches are not working, and if I need this ClusterRoleBinding? 

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-node-labeler-patcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-labeler
subjects:
  - kind: ServiceAccount
    name: patcher
    namespace: grafana
```

2023-12-05 20:53 UTC, larsks commented
@computate, looking at the logs for the patch operator, we see the following errors after creating the Patch resource:

```
...: failed to list /v1, Kind=Secret: secrets is forbidden: User
"system:serviceaccount:grafana:patcher" cannot list resource "secrets" in API
group "" at the cluster scope

...: failed to list integreatly.org/v1alpha1, Kind=Grafana:
grafanas.integreatly.org is forbidden: User
"system:serviceaccount:grafana:patcher" cannot list resource "grafanas" in API
group "integreatly.org" at the cluster scope

...: Failed to watch /v1, Kind=Secret: failed to list /v1, Kind=Secret: secrets
is forbidden: User "system:serviceaccount:grafana:patcher" cannot list resource
"secrets" in API group "" at the cluster scope

...: Failed to watch integreatly.org/v1alpha1, Kind=Grafana: failed to list
integreatly.org/v1alpha1, Kind=Grafana: grafanas.integreatly.org is forbidden:
User "system:serviceaccount:grafana:patcher" cannot list resource "grafanas" in
API group "integreatly.org" at the cluster scope
```

It looks like a permissions issue; we'll need to add some RBAC to provide the necessary permissions.

2023-12-05 21:06 UTC, larsks commented
Add this RBAC to your pr and things seem to work as expected:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-patcher
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - integreatly.org
  resources:
  - grafanas
  verbs:
  - get
  - list
  - watch
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-patcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-patcher
subjects:
- kind: ServiceAccount
  name: patcher
  namespace: grafana
```

Following our organizational model, that should go into the `cluster-scope` application somewhere.

2023-12-05 21:20 UTC, larsks commented
> Following our organizational model, that should go into the cluster-scope application somewhere.

...or not, since I see the `grafana` application includes the subscription and other resources we would normally put in `cluster-scope`, so it's best to keep things together.

2023-12-05 21:37 UTC, larsks commented
@computate, looking at <https://github.com/grafana-operator/grafana-operator/blob/v3.6.0/documentation/env_vars.md> this patching may no longer be necessary. I'm not 100% positive; followed <https://github.com/grafana-operator/grafana-operator/issues/130> to find that link and I'm taking a closer look now.

2023-12-05 21:51 UTC, larsks commented
I think you ought to be able to do something like this...

In the Grafana resource:

```
  deployment:
    envFrom:
    - configMapRef:
        name: grafana-config-overrides
    - secretRef:
        name: grafana-secrets
```

And in grafana-secrets:

```
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
type: Opaque
data:
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "..."
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "..."
```

You should be patching `spec.config.server` via Kustomize, not via a dynamic Patch resource.

2023-12-05 23:16 UTC, larsks commented
@computate with this latest set of changes I think everything is working (and no more patch operator required).

2023-12-06 17:21 UTC, computate approved these changes
@larsks Nice work with the secretGenerator, ExternalSecrets, and environment variable substitutions, thanks!

2023-12-06 17:21 UTC, computate commented on grafana/base/grafanadatasources/grafanadatasource.yaml
> +    - name: application-logging
We need to remove the Loki datasources and replace it with the prometheus datasource instead, and make sure the Patch Operator is working to patch the Bearer token in here: 
```yaml
  datasources:
    - access: proxy
      editable: false
      isDefault: true
      jsonData:
        httpHeaderName1: Authorization
        timeInterval: 5s
        tlsSkipVerify: true
      name: Prometheus
      secureJsonData:
        httpHeaderValue1: >-
          Bearer ...
      type: prometheus
      url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091/'
  name: custom-observability-grafana
  ```

2023-12-06 17:21 UTC, computate commented on grafana/base/grafanas/grafana.yaml
> +      root_url: $GRAFANA_ROOT_URL
I have applied this suggestion.

2023-12-06 17:21 UTC, computate commented on grafana/base/routes/route.yaml
> +  host: grafana.apps.nerc-ocp-infra.rc.fas.harvard.edu
I have applied this suggestion.

2023-12-06 17:21 UTC, computate commented on grafana/base/serviceaccounts/serviceaccount.yaml
> +---
I have applied this suggestion.

2023-12-06 17:21 UTC, computate commented on grafana/base/kustomization.yaml
> +  #  - grafanadatasources
I have applied this suggestion.

2023-12-06 19:36 UTC, schwesig approved these changes
@larsks awesome work, thanks for having these ideas/digging them up. appreciated.
Also thanks for getting me all the details in our call.

2023-12-06 20:34 UTC, computate commented on grafana/overlays/nerc-ocp-infra/grafanadatasources/observability-metrics.yaml
> +      url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091/'
@harshil-codes pointed out that we should change the url here to be the correct observability thanos querier `http://observability-thanos-query.open-cluster-management-observability.svc.cluster.local:9090`

2023-12-06 21:04 UTC, computate commented on grafana/overlays/nerc-ocp-infra/grafanadatasources/observability-metrics.yaml
> +      url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091/'
@schwesig @larsks  I just added a commit to change this URL while making another change to add a ClusterRoleBinding for the grafana-servicaccount to read the metrics.

2023-12-06 21:35 UTC, schwesig approved these changes

2023-12-06 21:36 UTC, schwesig approved these changes

2023-12-06 21:38 UTC, larsks approved these changes

2023-12-06 21:41 UTC, merged