WIP (do not merge yet) Feature/loki log forwarding
OCP-on-NERC/nerc-ocp-config pull request #48
Opened 2022-08-01 19:12 UTC by computate

loki log forwarding

If I Unmanage the Loki Operator and update this configmap `oc --as system:admin -n openshift-operators-redhat get configmap/lokistack-config -o yaml` with the ca_file configured, I get a little closer to getting loki working with the S3 storage: 

```yaml
    common:
      storage:
        s3:
          s3: https://s3.openshift-storage.svc
          bucketnames: loki-objectbucketclaim-f1a5fca3-cfed-4b7b-9415-d9c42f862ba4
          region: 
          access_key_id: VLxavb1vfE2OB6fYY22L
          secret_access_key: Wf6DMNsgRARYHE5XvLNQUqm7qSID75tAZTAqXHhh
          s3forcepathstyle: true
          http_config:
            ca_file: "/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
```

The tricky part is that the Loki Operator does not let you configure the CA Cert in the config it generates, see this part that doesn't have options for http_config ca_file: 

https://github.com/grafana/loki/blob/main/operator/internal/manifests/internal/config/loki-config.yaml#L21-L29

The loki documentation also let's you specify these command parameters that also work if the operator is unmanaged (CLI flag: -<prefix>.s3.http.ca-file): 

https://grafana.com/docs/loki/latest/configuration/

I can add this to the args in the lokistack-sample-index-gateway StatefulSet in the loki project: -s3.http.ca-file=/run/secrets/kubernetes.io/serviceaccount/service-ca.crt

But this is the part I don't quite have working, to connect Loki to the S3 bucket.

2022-08-17 21:03 UTC, naved001 reviewed
Thanks @computate! This is a lot of work.

Here are my initial thoughts:

* There should be an argocd app for Loki and Grafana. And that app should be deploying all the namespaced resources for loki/grafana like deployments, routes, externalsecrets etc. The `cluster-scope` app should only be used for deploying clusterwide things (clusterrolebindings, creating new namespaces, operator subscriptions etc). 
* It would be nice if we could organize this PR into multiple commits to make it easier to review. I will not block the PR on that, that's merely a suggestion.
* Could you link to some documentation that you referred to while creating these resources? That way I can better understand whats going on in this PR. Ideally the link to relevant documentation should be a part of the commit message.

I will leave a more thorough review soon-ish.

2022-08-18 13:17 UTC, computate commented
Thanks for the suggestions @naved001 @joachimweyl , I can take a look at implementing your suggestions after I get back from vacation on Monday. Meanwhile, I have added all the useful documentation links in the top description of the PR.

2022-08-19 19:37 UTC, naved001 requested changes

2022-08-19 19:37 UTC, naved001 commented on cluster-scope/base/core/namespaces/openshift-logging/namespace.yaml
> +spec: {}
why is `spec` specified here? I didn't see it in the redhat document that describe this namespace.

2022-08-19 19:37 UTC, naved001 commented on cluster-scope/base/core/namespaces/openshift-logging/namespace.yaml
> +spec: {}
same thing with the other namespaces. Just curious what does setting `spec` to `{}` do for a namepsace.

2022-08-19 19:37 UTC, naved001 commented on cluster-scope/base/operators.coreos.com/subscriptions/grafana-operator/subscription.yaml
> +  name: loki-operator
this should be `grafana-operator`

2022-08-19 19:37 UTC, naved001 commented on cluster-scope/base/operators.coreos.com/subscriptions/cluster-logging/subscription.yaml
> +  name: loki-operator
this should be `cluster-logging`

2022-08-19 19:37 UTC, naved001 commented on cluster-scope/base/external-secrets.io/externalsecrets/lokistack-config-custom/externalsecret.yaml
> +namespace: openshift-operators-redhat
`namespace` should only be under `metadata`. Specifying it here makes this invalid and this manifest won't be deployed.

2022-08-19 19:37 UTC, naved001 commented on cluster-scope/base/external-secrets.io/externalsecrets/openshift-logging-lokistack-gateway-bearer-token/externalsecret.yaml
> +namespace: openshift-logging
same; `namespace` should be removed from here.

2022-08-19 19:37 UTC, naved001 commented on cluster-scope/overlays/nerc-ocp-infra/externalsecrets/openshift-logging-lokistack-gateway-bearer-token_patch.yaml
> +namespace: openshift-logging
`namespace` should be removed from here.

2022-08-19 19:37 UTC, naved001 commented on cluster-scope/overlays/nerc-ocp-infra/externalsecrets/loki-config-custom_patch.yaml
> +namespace: openshift-operators-redhat
`namespace` should be removed from here.

2022-08-25 19:56 UTC, computate commented
I'm going to close this PR and simplify these updates into smaller PRs based on Naved's great suggestion for argocd apps.

2022-08-25 19:56 UTC, closed without merging

2022-08-26 13:15 UTC, joachimweyl commented
@computate please link smaller PR's here.

2022-08-26 17:50 UTC, computate commented
@joachimweyl Here are the new smaller prs: 
https://github.com/OCP-on-NERC/nerc-ocp-config/pull/69
https://github.com/OCP-on-NERC/nerc-ocp-config/pull/70
https://github.com/OCP-on-NERC/nerc-ocp-config/pull/71
https://github.com/OCP-on-NERC/nerc-ocp-apps/pull/9