Fix duration in ingress cert on beta cluster
OCP-on-NERC/nerc-ocp-config pull request #496
Opened 2024-08-19 15:11 UTC by tssala23

Value set to 360h0m0s instead of 2160h0m0s

2024-08-19 20:37 UTC, dystewart approved these changes

2024-08-19 20:39 UTC, dystewart commented
I'm curious if the cluster will complain about updating the cert, or if it'll need to be recreated

2024-08-19 20:41 UTC, tssala23 commented
> I'm curious if the cluster will complain about updating the cert, or if it'll need to be recreated

I’ve already applied the correct cert to the cluster. It never created the cert due to that value being incorrect

2024-08-22 17:42 UTC, larsks requested changes
It would be great to see more information in the commit message (what was the problem, what's 2160h in days, what the behavior was with the previous value, etc)

2024-08-22 17:46 UTC, larsks commented
I have updated this PR to (a) fix the namespace in which we're creating the default-ingress-certificate and (b) include more information in the commit message.

2024-08-22 17:46 UTC, larsks approved these changes

2024-08-22 19:45 UTC, merged