External ingress
OCP-on-NERC/nerc-ocp-config pull request #50
Opened 2022-08-05 15:59 UTC by chrisstafford

2022-08-05 16:01 UTC, chrisstafford commented
I still need to create the secrets for the certificate and still need clarity on whether or not we want an API endpoint exposed outside the network. I would however like a sanity check that this at least looks correct.

2022-08-05 20:43 UTC, larsks requested changes
I've requested one specific change, but I'd like to make a couple more broad suggestions.

I prefer to see pull requests on a particular feature (e.g., this one would be "Configure external ingress"). Things that are dependencies of that feature, but not directly related (like configuring secret stores, or configuring the API certificate) should be split out into separate pull requests. This has a bunch of advantages:

- Smaller pull requests are easier to review
- It allows us to merge the dependencies while still working on other parts of the PR
- It may enable other folks to work on unrelated pull requests that share the same dependencies

2022-08-05 20:43 UTC, larsks commented on cluster-scope/overlays/nerc-ocp-prod/clustersecretstores/nerc-cluster-secrets_patch.yaml
> +apiVersion: external-secrets.io/v1beta1
For the production cluster,  we're going to want per-namespace secretstores. A cluster-wide secret store would potentially expose sensitive secrets to all cluster users.

2022-08-05 20:43 UTC, larsks commented on cluster-scope/overlays/nerc-ocp-prod/ingresscontrollers/external-apps.ingress-controller.yaml
> +apiVersion: operator.openshift.io/v1
This ingress controller needs to be configured to listen on a public address. That means we're first going to need to configure an appropriate interface on all the worker nodes (so probably a `NodeNetworkConfigurationPolicy` resource), and then we're going to need to perform some work -- of which I don't know the specifics -- to bind the ingress controller to the public address.

2022-08-08 16:25 UTC, chrisstafford commented
@larsks, I agreeon all points, I just branched this from a branch still waiting to be merged. I'll close this PR and create a new branch from main and include your changes.

2022-08-19 18:39 UTC, naved001 commented
@chrisstafford should this be closed?

2022-09-07 12:14 UTC, joachimweyl commented
@chrisstafford ^

2022-09-08 13:36 UTC, closed without merging