Increase rhods-notebooks requests.storage to 4Ti
OCP-on-NERC/nerc-ocp-config pull request #513
Opened 2024-08-28 14:20 UTC by computate

With 140 students starting Prof. Leonidas Rust course requiring 20Gi PVC
per student (140 students × 20Gi = 2,800Gi) We should increase the
rhods-notebooks requests.storage to at least 4Ti.

2024-08-29 19:39 UTC, Milstein approved these changes
LGTM

2024-08-29 19:45 UTC, Milstein requested changes
Course | Total Students/ TAs/ Instructors
-------- | -----------------------------------
DS210  |  145
CS210  |  300

Required each PVC per student = 20 GiB
450*20 GiB to TiB = 8.78 TiB

2024-08-30 14:44 UTC, Milstein approved these changes
LGTM to cover 2 Fall classes

2024-08-30 14:55 UTC, schwesig approved these changes

2024-08-30 20:31 UTC, merged