increase pvc size to 20gb
OCP-on-NERC/nerc-ocp-config pull request #518
Opened 2024-08-30 14:57 UTC by DanNiESh

2024-08-30 15:03 UTC, schwesig approved these changes

2024-08-30 20:33 UTC, computate approved these changes

2024-09-01 01:15 UTC, larsks requested changes
Please update the commit message and pull request description to indicate *which* pvc we're increasing.

2024-09-03 17:25 UTC, DanNiESh commented
@larsks Let me know if the change looks good

2024-09-03 18:18 UTC, larsks approved these changes

2024-09-03 18:19 UTC, larsks commented
Looks good, thanks!

2024-09-03 18:39 UTC, merged