Add oauth-proxy imagestream
OCP-on-NERC/nerc-ocp-config pull request #543
Opened 2024-09-24 18:50 UTC by IsaiahStapleton

This image is used by RHOAI to provide authentication. RHOAI is currently pulling this image externally but we would like to store it and pull from the internal image repo.

2024-09-24 18:53 UTC, computate commented
@IsaiahStapleton Don't forget to enable the pre-commit-checks so you don't miss the yaml validation issues. 
https://github.com/OCP-on-NERC/nerc-ocp-config?tab=readme-ov-file#pre-commit-checks

2024-09-24 19:11 UTC, IsaiahStapleton commented
@computate Fixed, thanks

2024-09-24 19:20 UTC, computate reviewed
@IsaiahStapleton Why are we introducing the exact image that already exists? 

```bash
$ oc -n redhat-ods-applications get imagestream/oauth-proxy -o yaml | grep from: -A 2
    from:
      kind: DockerImage
      name: registry.redhat.io/openshift4/ose-oauth-proxy@sha256:4bef31eb993feb6f1096b51b4876c65a6fb1f4401fee97fa4f4542b6b7c9bc46
```

2024-09-24 19:20 UTC, DanNiESh approved these changes

2024-09-24 19:31 UTC, IsaiahStapleton commented
@computate The image already exists in redhat-ods-applications because I manually applied it there. I created this PR so we have a record of it and so ArgoCD can manage it (in the case resources get deleted). The reason I used the exact sha256 is because that is the exact one RHOAI uses but it pulls from an external registry. Last semester when Red Hat's registry was down students couldn't start pods because RHOAI was trying to pull this oauth-proxy container from the external registry rather than the internal one. So the idea was to store the image internally and then use a Gatekeeper policy to change where the pods are pulling the oauth-proxy container from. The relevant issue is here: https://github.com/nerc-project/operations/issues/506.

2024-09-24 20:21 UTC, larsks requested changes
This needs to be included in a kustomization file.

2024-09-26 15:27 UTC, computate approved these changes

2024-09-26 15:37 UTC, larsks approved these changes

2024-09-26 15:37 UTC, merged