Adding postgresql-ha on obs cluster
OCP-on-NERC/nerc-ocp-config pull request #591
Opened 2024-11-04 16:23 UTC by RH-csaggin

- created all the postgresql-ha config resources for the ai-telemetry project
- creation of external secrets
- creation of namespace

2024-11-04 16:49 UTC, computate requested changes

2024-11-04 16:49 UTC, computate commented on ai-telemetry/overlays/nerc-ocp-obs/externalsecrets/postgresql-ha-pgpool-externalsecret.yaml
> +  name: postgresql-ha-pgpool-secret
Check that the name here matches the other part of this ExternalSecret.

2024-11-04 16:49 UTC, computate commented on ai-telemetry/base/externalsecrets/postgresql-ha-secret.yaml
> +  name: postresql-ha-secret
Check that the name here matches the patch for this ExternalSecret.

2024-11-04 16:50 UTC, computate requested changes

2024-11-04 16:50 UTC, computate commented on ai-telemetry/base/externalsecrets/postgresql-ha-pgpool-secret.yaml
> +  name: postgresql-ha-pgpool
Check that the name here matches the patch for this ExternalSecret.

2024-11-05 12:50 UTC, RH-csaggin commented
@computate Well spotted I have one conflict name plus another typo. Now looks good.

2024-11-06 15:19 UTC, computate requested changes

2024-11-06 15:19 UTC, computate commented on ai-telemetry/base/postgresql-ha/statefulset.yaml
> +                  name: postgresql-ha-postgresql
This should be `postgresql-ha-secret`.

2024-11-06 15:19 UTC, computate commented on ai-telemetry/base/postgresql-ha/statefulset.yaml
> +                  name: postgresql-ha-postgresql
This should be `postgresql-ha-secret`.

2024-11-06 15:19 UTC, computate commented on ai-telemetry/base/postgresql-ha/deployment.yaml
> +                  name: postgresql-ha-postgresql
This should be `postgresql-ha-secret`.

2024-11-06 15:19 UTC, computate commented on ai-telemetry/base/postgresql-ha/deployment.yaml
> +                  name: postgresql-ha-postgresql
This should be `postgresql-ha-secret`.

2024-11-06 15:19 UTC, computate commented on ai-telemetry/base/externalsecrets/postgresql-ha-secret.yaml
> +    name: postresql-ha-secret
This should be `postgresql-ha-secret`.

2024-11-12 16:35 UTC, computate commented
Replacing this PR [with another PR](https://github.com/OCP-on-NERC/nerc-ocp-config/pull/597) containing the latest from the main branch, and some fixes to the secret names.

2024-11-14 16:45 UTC, computate commented
Closing this, we will use Crunchy Postgres instead.

2024-11-14 16:45 UTC, closed without merging