nerc-ocp-prod: Fix None acceleratorProfile in RHOAI
OCP-on-NERC/nerc-ocp-config pull request #618
Opened 2024-12-03 15:36 UTC by dystewart

Addresses: https://github.com/nerc-project/operations/issues/685

In https://github.com/OCP-on-NERC/nerc-ocp-config/pull/566 we tested this clusterpolicy config change with success. This PR will bring the change to the prod RHOAI installation.

Marking as a draft for now, since this will require some of the operator pods to reconfigure we should tactically merge this on off hours.

2025-01-08 21:21 UTC, jtriley requested changes

2025-01-08 21:21 UTC, jtriley commented on nvidia-gpu-operator/overlays/nerc-ocp-prod/clusterpolicy/clusterpolicy_patch.yaml
> +      - name: ACCEPT_NVIDIA_VISIBLE_DEVICES_AS_VOLUME_MOUNTS
This is already active in the base gpu cluster policy so no need to include in the patch.

2025-01-14 21:11 UTC, jtriley approved these changes

2025-01-14 21:12 UTC, jtriley requested changes

2025-01-14 21:12 UTC, jtriley commented on nvidia-gpu-operator/overlays/nerc-ocp-prod/clusterpolicy/clusterpolicy_patch.yaml
> +    enabled: true
This is also redundant as it's already true in base

2025-01-14 21:16 UTC, jtriley approved these changes

2025-01-14 21:24 UTC, aabaris approved these changes

2025-01-14 21:37 UTC, merged