Feature/loki operator
OCP-on-NERC/nerc-ocp-config pull request #69
Opened 2022-08-26 16:58 UTC by computate

This is to add loki-operator as an app to the project. 
Documentation for this task can be found in many links here:

    https://loki-operator.dev/docs/forwarding_logs_to_gateway.md/
    https://grafana.com/docs/loki/latest/api/#push-log-entries-to-loki

2022-08-26 18:22 UTC, dystewart requested changes

2022-08-26 18:22 UTC, dystewart commented on .gitignore
>  **/overlays/*-local/
Remove this file from commit?

2022-08-29 17:54 UTC, naved001 commented on loki/base/clusterrolebindings/lokistack-gateway-auth-delegator.yaml
> +    name: lokistack-gateway
Where is this ServiceAccount created?

2022-08-29 17:54 UTC, naved001 commented on loki/base/clusterrolebindings/lokistack-tenant-logs.yaml
> +  name: logcollector
same; how's this created?

2022-08-29 18:07 UTC, dystewart approved these changes

2022-08-30 13:20 UTC, joachimweyl commented
@dystewart was your CR resolved to your expectation?

2022-08-30 19:03 UTC, merged

2022-08-30 21:42 UTC, naved001 commented on loki/base/clusterrolebindings/lokistack-gateway-auth-delegator.yaml
> +    name: lokistack-gateway
@computate Just wanted to make sure you saw my questions on this PR before this was merged. Perhaps, I should have used the "request changes" button.