Add OpenShift Pipelines operator to infra cluster
OCP-on-NERC/nerc-ocp-config pull request #77
Opened 2022-09-07 04:37 UTC by dystewart

This PR is to add the OpenShift Pipelines Operator subscription to fix the argoCD sync error we're seeing in argoCD relating to the vault backup job. 

The job uses custom resources such as `task` and `taskRun`, which are added to the cluster through this operator. 

Once merged we should be able to sync the vault resources in argoCD.

2022-09-07 15:00 UTC, computate approved these changes

2022-09-07 17:37 UTC, naved001 requested changes
Should we be consider disabling the creation of clusterwide RBACs that may be a potential security issue? I know we won't have users on the infra cluster, so it may be okay, but I wanted to run this by folks @jtriley @larsks 

https://docs.openshift.com/container-platform/4.10/cicd/pipelines/installing-pipelines.html#op-disabling-automatic-creation-of-rbac-resources_installing-pipelines

2022-09-09 18:29 UTC, naved001 approved these changes

2022-09-12 14:51 UTC, joachimweyl commented
@dystewart is this ready for merge?

2022-09-12 16:49 UTC, merged